function [F_N,ddz_w] = SupportDetection(F,L0,L0_dot,L0_ddot,Tp,ddtheta,ddz_M,dtheta,theta)
%SupportDetection
%    [F_N,DDZ_W] = SupportDetection(F,L0,L0_dot,L0_ddot,Tp,DDTHETA,ddz_M,DTHETA,THETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-05-14 16:10:44

t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
F_N = ddz_M.*(3.0./2.0e+1)+F.*t2-L0_ddot.*t2.*(3.0./2.0e+1)+L0.*ddtheta.*t3.*(3.0./2.0e+1)+L0_dot.*dtheta.*t3.*(3.0./1.0e+1)+L0.*t2.*t4.*(3.0./2.0e+1)+(Tp.*t3)./L0+1.4715;
if nargout > 1
    ddz_w = ddz_M-L0_ddot.*t2+L0.*ddtheta.*t3+L0_dot.*dtheta.*t3.*2.0+L0.*t2.*t4;
end
end
