function T12 = VMC(F,T,l,l1,l2,q1,q2)
%VMC
%    T12 = VMC(F,T,L,L1,L2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-12-08 16:31:36

t2 = l1.^2;
t3 = 1.0./l2;
t5 = T./2.0;
t6 = q1./2.0;
t7 = q2./2.0;
t4 = t3.^2;
t8 = -t7;
t9 = t6+t8;
t10 = sin(t9);
t11 = t10.^2;
t12 = t2.*t4.*t11;
t13 = -t12;
t14 = t13+1.0;
t15 = 1.0./sqrt(t14);
t16 = (F.*l.*l1.*t3.*t10.*t15)./2.0;
T12 = [t5-t16;t5+t16];
end
