function out1 = serialVMC(F,T,L0,phi,theta1,theta2)
%serialVMC
%    OUT1 = serialVMC(F,T,L0,PHI,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-05-03 16:43:33

t2 = cos(phi);
t3 = cos(theta1);
t4 = sin(phi);
t5 = sin(theta1);
t6 = theta1+theta2;
t7 = 1.0./L0;
t8 = cos(t6);
t9 = sin(t6);
t10 = t3.*(9.0./5.0e+1);
t11 = t5.*(9.0./5.0e+1);
t12 = -t10;
t13 = -t11;
t14 = t8.*(9.0./4.0e+1);
t15 = t9.*(9.0./4.0e+1);
t16 = t12+t14;
t17 = t13+t15;
out1 = [-F.*(t2.*t17-t4.*t16)-T.*t7.*(t2.*t16+t4.*t17),F.*(t4.*t8.*(9.0./4.0e+1)-t2.*t15)-T.*t7.*(t2.*t14+t4.*t15)];
end
